winzou_state_machine:
  sylius_payment:
    callbacks:
      before:
        robier_sylius_croatian_fiscalization_plugin_fiscalize:
          on: ['complete']
          do: ['@robier_sylius_croatian_fiscalization_plugin.event_producer.fiscalize', '__invoke']
          args: ['object']

sylius_ui:
  events:
    sylius.admin.order.show.summary:
      blocks:
        robier_sylius_croatian_fiscalization_plugin:
          template: '@RobierSyliusCroatianFiscalizationPlugin/Order/Admin/fetchFiscalizationData.html.twig'
          priority: 15
