version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch01
      - cluster.name=elasticsearch-cluster
      - discovery.type=single-node
      - node.name=elasticearch01
      - bootstrap.memory_lock=true
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
      # health check script
      - ../scripts/healthcheck/elasticsearch:/usr/local/bin/docker-health-check
    healthcheck:
      test: [ 'CMD', 'docker-health-check' ]

volumes:
  elasticsearch: