version: '3.7'

services:
  nginx:
    hostname: nginx
    image: nginx:1.21.1-alpine
    volumes:
      # configuration
      - ../configurations/nginx/${NGINX_CONFIG_TARGET}.conf:/etc/nginx/conf.d/default.conf
      - ../../:/app/
