version: '3.7'

services:
  node:
    hostname: node
    build:
      context: ../
      dockerfile: ./images/node.Dockerfile
      args:
        HOST_USER_ID: ${DOKMAN_HOST_USER_ID}
        HOST_GROUP_ID: ${DOKMAN_HOST_GROUP_ID}
    image: ${COMPOSE_PROJECT_NAME}/node:1.0
    volumes:
      # configuration
      - ../../:/app/
    working_dir: /app
